version: '3.8'

services:
  db:
    container_name: postgres
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "80:5432"
